# Generated by Django 5.0 on 2024-01-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='additem',
            name='cid',
        ),
    ]
