# Generated by Django 5.0 on 2023-12-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_invoice_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimates',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
