# Generated by Django 5.0 on 2024-02-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_remove_additem_available_stock_remove_additem_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_item',
            name='inv_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
