# Generated by Django 5.0 on 2024-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_invoice_item_inv_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
