# Generated by Django 5.0 on 2023-12-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_remove_estimates_invoice_invoice_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicepayment',
            old_name='bank',
            new_name='banking',
        ),
    ]
