# Generated by Django 5.0 on 2024-03-21 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_alter_additem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addgodown',
            name='additem',
        ),
        migrations.RemoveField(
            model_name='comments_item',
            name='item',
        ),
        migrations.RemoveField(
            model_name='credititem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='p',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='itemtable',
        ),
        migrations.RemoveField(
            model_name='recurring_invoice',
            name='items',
        ),
        migrations.RemoveField(
            model_name='retaineritems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sales_item',
            name='item',
        ),
        migrations.AddField(
            model_name='unit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
