# Generated by Django 5.0 on 2023-12-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_inventoryadjust_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='reason',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
