# Generated by Django 5.0 on 2024-01-05 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_alter_reason_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pterms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.payment_terms'),
        ),
    ]
