# Generated by Django 5.0 on 2024-01-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_invoice_pterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
