# Generated by Django 5.0 on 2024-03-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_purchase_user_reason_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='user',
        ),
    ]
