# Generated by Django 5.0 on 2024-01-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_invoicepayment_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, upload_to='invoice_attachments/')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.loan')),
            ],
        ),
    ]
