# Generated by Django 5.0 on 2024-01-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_invoiceattach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceattach',
            name='loan',
        ),
        migrations.AddField(
            model_name='invoiceattach',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.invoice'),
        ),
    ]
