# Generated by Django 5.0 on 2024-03-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_reason_user_alter_reason_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(choices=[('BOX', 'Box'), ('UNIT', 'Unit'), ('LITER', 'Liter')], max_length=255),
        ),
    ]
